export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'refactor', 'test', 'docs', 'chore', 'ci', 'perf', 'style', 'revert'],
    ],
   'scope-enum': [
  2,
  'always',
  [
    'auth',
    'users',
    'roles',
    'customers',
    'vendors',
    'products',
    'skus',
    'inventory',
    'lots',
    'boxes',
    'orders',
    'allocations',
    'shipments',
    'logistics',
    'bol',
    'packing-slips',
    'invoices',
    'credits',
    'reconciliation',
    'commissions',
    'margins',
    'quickbooks',
    'hubspot',
    'fresho',
    'sheets',
    'email-parser',
    'notifications',
    'dashboards',
    'reports',
    'forecasting',
    'migration',
    'mana-transition',
    'audit',
    'api',
    'web',
    'workers',
    'infra',
    'docs',
    'shared',
    'root',
  ],
],
    'type-case': [2, 'always', 'lowercase'],
    'scope-case': [2, 'always', 'lowercase'],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
  },
};
